_test_scripts: &_test_scripts
  before_install:
    - mysql -e 'CREATE DATABASE last-mile-delivery;'
  script:
    - yarn test

env:
  global:
    - PORT=8080
    - LOG_FORMAT=json
    - SQL_DATABASE=last-mile-delivery
    - SQL_HOST=127.0.0.1
    - SQL_PASSWORD=
    - SQL_USERNAME=travis
    - SQL_DIALECT=mysql
    - SQL_OPERATOR_ALIASES=false
    - SQL_SEEDER_STORAGE=sequelize
    - SQL_SEEDER_STORAGE_TABLE_NAME=SequelizeData

services:
  - mysql

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - language: node_js
      node_js: "10"
      <<: *_test_scripts

    - language: node_js
      node_js: "11"
      <<: *_test_scripts

    - language: node_js
      node_js: "12"
      <<: *_test_scripts
