export const {
  PORT,
  LOG_FORMAT,
  GOOGLE_MAPS_API_KEY,
  SQL_DATABASE,
  SQL_DIALECT,
  SQL_HOST,
  SQL_OPERATOR_ALIASES,
  SQL_PASSWORD,
  SQL_SEEDER_STORAGE,
  SQL_SEEDER_STORAGE_TABLE_NAME,
  SQL_USERNAME
} = process.env;
